name: Build apk and create release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # - uses: subosito/flutter-action@v1
    #   with:
    #     flutter-version: '2.0.2'
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: create tag
      working-directory: bash-scripts
      run: bash ./create-tag.sh
      id: created_tag
    - run: echo steps.created_tag.outputs.new_tag
    # - run: flutter pub get
    # - run: flutter analyze .
    # - run: flutter build apk --split-per-abi
    # - name: Set path to apks into the path.content
    #   run: echo "::set-output name=content::$(echo $(pwd)/build/app/outputs/flutter-apk/*.apk | tr ' ' ,)"
    #   id: path
    # - name: Create a Release in GitHub
    #   if: ${{ steps.created_tag.outputs.should_release == 'true' }}
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: ${{ steps.path.outputs.content }}
    #     token: ${{ secrets.GH_TOKEN }}
    #     tag: ${{ steps.created_tag.outputs.new_tag }}
    #     commit: ${{ github.sha }}
    #     prerelease: true 